### ISSUE TITLE
Error when using calculated fields

### ISSUE THREAD

**Issue by enfJoao** [SCullman/DNN.FormAndList#7]
When I added a calculated field based on [intfield] + 10, I tested it editing some rows and the field was calculated fine.

However, when I try to create a new record, the green confirmation did not show, no error was shown on screen, and the link had: /def/errormessage

Checked the admin logs and I had this:
```
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:b4bad84e-6b90-4255-84eb-e6694121bf63
AssemblyVersion:9.1.1
PortalId:0
UserId:1
TabId:219
RawUrl:/...
Referrer:https://...
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
ExceptionHash:QKZuiSMY28G3MbdBenUr2XM7FWU=
Message:The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).
StackTrace:
InnerMessage:The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).
InnerStackTrace:
at System.Web.UI.ControlCollection.Add(Control child) at DotNetNuke.Services.Exceptions.Exceptions.ProcessModuleLoadException(String FriendlyMessage, Control ctrl, Exception exc, Boolean DisplayErrorMessage)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: ...

ModuleId:864
ModuleDefId:134
FriendlyName:Form and List
ModuleControlSource:DesktopModules/UserDefinedTable/Default.ascx
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:96179f9a-4a6a-47ac-b035-1b2d1af5d045
AssemblyVersion:9.1.1
PortalId:0
UserId:1
TabId:219
RawUrl:/...
Referrer:https://...
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
ExceptionHash:EQDfGxtjEmUKwh4x8o9tEIVTw1U=
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
at DotNetNuke.Modules.UserDefinedTable.DataTypes.EditString.get_Value() at DotNetNuke.Modules.UserDefinedTable.EditForm.cmdUpdate_Click(Object sender, EventArgs e)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: ...
```

Deleted the calculated field, and it worked fine again.

**Comment by SCullman** [comment]
Any chance that the number was bigger than 999? Then it is the same issue as #6

**Comment by enfJoao** [comment]
Way bigger.

Not sure how it is related, but when using the int field only, it does not
give any error. Only when I add a calculated field based on that int.

**Comment by SCullman** [comment]
Should have been fixed in fnl.6.3.3
